name: Publish SplineRuntime.xcframework

on:
  repository_dispatch:
    types: [runtime_publish]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.client_payload.version }}
      SOURCE_REPO: ${{ github.event.client_payload.source_repo }}
    steps:
      - name: Generate token from spline-bot
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.SPLINE_BOT_APP_ID }}
          private_key: ${{ secrets.SPLINE_BOT_APP_KEY }}
          repositories: >-
            ["spline-ios", "spell"]

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Download the zip
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh release download "$VERSION" \
            --repo "$SOURCE_REPO" \
            --pattern "SplineRuntime_$VERSION.zip" \
            --clobber

      - name: Remove old SplineRuntime.xcframework
        run: rm -rf SplineRuntime.xcframework

      - name: Unzip SplineRuntime.xcframework
        run: unzip -o "SplineRuntime_$VERSION.zip"

      - name: Delete the zip
        run: rm "SplineRuntime_$VERSION.zip"

      - name: Push the changes
        run: |
          git config user.name "spline-bot[bot]"
          git config user.email "spline-bot[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add -A
            git commit -m "Release $VERSION"
            git push
          else
            echo "No local changes detected."
          fi
